forca/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from forcaapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('game-fail/', TemplateView.as_view(template_name='final.html'), name='final-game'),
     path('game-sucess/', TemplateView.as_view(template_name='sucess.html'), name='game-sucess'),
    path('', include('forcaapp.urls'), name='forcaapp'),
    path('inmatch/', views.inMatch.as_view(), name='match'),
]

forcaapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

class Partida(models.Model):
	userId = models.PositiveIntegerField(validators=[MinValueValidator(0)], verbose_name='id-user', default=0)
	allTrue = models.BooleanField(default=False, verbose_name='final')
	image = models.PositiveIntegerField(validators=[MinValueValidator(0)], verbose_name='image', default=1)
	state = models.BooleanField(default=True, verbose_name='estado')
	dica = models.CharField(max_length=150, verbose_name='dica')

	def __str__(self):
		return 'partida'
	  
	class Meta:
		verbose_name = 'partida'
		verbose_name_plural = 'partidas'

class Profile(models.Model):
	userName = models.CharField(max_length=150, verbose_name='userName')
	userId = models.PositiveIntegerField(validators=[MinValueValidator(0)], verbose_name='id-user', default=0)
	Individualpontos = models.PositiveIntegerField(validators=[MinValueValidator(0)], verbose_name='pointsI', default=0)

	def __str__(self):
		return ('User' + str(self.userId))
	  
	class Meta:
		verbose_name = 'User'
		verbose_name_plural = 'Users'

class Palavra(models.Model):
	palavra = models.CharField(max_length=150, verbose_name='palavra')
	dica = models.CharField(max_length=150, verbose_name='dica')

	def __str__(self):
		return self.palavra
	  
	class Meta:
		verbose_name = 'palavra'
		verbose_name_plural = 'palavras'

class Letras(models.Model):
	letra = models.CharField(max_length=150, verbose_name='letra')
	partidaId = models.PositiveIntegerField(validators=[MinValueValidator(0)], verbose_name='id-partida', default=0)
	visible = models.BooleanField(default=False, verbose_name='visivel')

	def __str__(self):
		return self.letra
	  
	class Meta:
		verbose_name = 'letra'
		verbose_name_plural = 'letras'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Base file{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:200" rel="stylesheet">
  <style>
  	
  	.input-margin{
  		margin-top: 30px;
  	}
  	body {
   	background-image: url('https://chupacdn.s3.amazonaws.com/catalog/product/cache/5/thumbnail/1280x/17f82f742ffe127f42dca9de82fb58b1/6/-/6-vector-game-backgrounds-8003_imgs_8003_2.png');
   	background-color: #cccccc;
}

#main{
  width: 500px;
  height: 300px;
  margin: 50px auto;
  border-radius: 50px;
}
#main3{
  width: 700px;
  height: 300px;
  margin: 30px auto;
  border-radius: 50px;
}

#main2{
  width: 400px;
  height: 460px;
  margin: 50px auto;
  border-radius: 50px;
}
#main4{
  width: 400px;
  height: 200px;
  margin: 50px auto;
  border-radius: 50px;
}

.box {
    width:300px;
    height:300px;
    position:fixed;
    margin-left:-150px; /* half of width */
    margin-top:-150px;  /* half of height */
    top:50%;
    left:50%;
}

.block-color{
	background-color: #ffffff;
}
h1{
	font-family: 'Montserrat', sans-serif;
}
h2{
  font-family: 'Montserrat', sans-serif;
}
label{
	font-family: 'Montserrat', sans-serif;
}
h4{
	font-family: 'Montserrat', sans-serif;
}

.title-h1{
  position: relative;
  top: 50%;
  transform: translatey(-50%);
}

.text-relative{
    background-color: #ffffff;
    max-width: 300px;
    border-radius: 50px;
    margin: 0px auto;
    padding: 0px;
    word-break: break-all; 
}

  </style>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/confirm.html
{% extends 'base.html' %}

{% block title %}Comentário{% endblock %}

{% block content %}


<div id="main4" class="block-color" style="text-align: center;">
    {% if user.is_authenticated %}
        <h1>Confirme a criação</h1><br>
        <form method="post" class="form-signin">
            {% csrf_token %}
            <div style="display: none;">
            {{ form.as_p }}
            </div>
            <button class="btn btn-secundary" type="submit">Confirmo</button>
        </form> <br>
        <button onclick="window.location.href='/'" class="btn btn-primary" style="display: inline;">Home</button>
        
    {% else %}
        <META http-equiv="refresh" content="0;URL=/"> 
    {% endif %}
    
</div>

{% endblock %}

templates/create-word.html
{% extends 'base.html' %} 
{% block title %}Criar Palavra{% endblock %}

{% block content %}

<div id="main2" class="block-color" style="text-align: center;">
<div class="top-buffer">    
    <div class="mx-auto" style="width: 300px;">
        <div class="col-sm-20 text-center" >
        <img style="margin-top: 10px;" class="img-fluid" alt="Responsive image" height="90" width="90" src="https://cdn6.aptoide.com/imgs/3/0/8/3085b9e7d65213201733dd0088da037a_icon.png?w=240" >
        <h1>Criação de palavras</h1>
        <div style="margin-top:20px;">
        <form method="POST" class="form-signin">
                {% csrf_token %}
                <p>Atenção use apenas letras minúsculas</p>
                <label class="container-fluid">Palavra:</label>
                <input type="text" name="palavra" maxlength="150" required="" id="id_palavra"><br>
                <label class="container-fluid">Dica:</label>
                <input type="text" name="dica" maxlength="150" required="" id="id_dica"><br>
                <br><button type="submit" name="submit" class="btn btn-primary">Criar palavra</button>
                <button style="margin: 5px;" onclick="window.location.href='/'"  class="btn btn-secundary">Home</button>
                </div>
                
        </form>
     </div>   
    </div>
    </div>
    </div>
    </div>

{% endblock %}

templates/final.html
{% extends 'base.html' %}

{% block title %}Game Over{% endblock %}

{% block content %}


    <div id="main" class="block-color" style="text-align: center;">
    {% if user.is_authenticated %}
        <div class="title-h1" ">
        <h1 >Você perdeu kkkk!</h1>
        </div>
        <META http-equiv="refresh" content="2;URL=/">
    {% else %}
        <META http-equiv="refresh" content="0;URL=/">
    {% endif %}
    
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}


<div id="main" class="block-color" style="text-align: center;">
	{% if user.is_authenticated %}
  		<h1>Enforcados INTIN</h1><br>
  		<div style="margin-top: 10px;">
  		<h1>Oi {{ user.username }}! Escolha uma das opções</h1><br>
  		<button onclick="window.location.href='/create-match'" style="margin: 5px;" class="btn btn-primary">Criar nova partida</button>
      <button onclick="window.location.href='/create-word'" style="margin: 5px;" class="btn btn-success">Criar nova palavra</button>
      <button onclick="window.location.href='/ranking'" style="margin: 5px;" class="btn btn-warning">Ranking</button>
  		<button onclick="window.location.href='/accounts/logout'" style="margin: 5px;" class="btn btn-danger">Sair</button>
  		</div>
  		
	{% else %}
		<h1 >Enforcados INTIN</h1>
  		<div style="margin-top: 40px;">
  		<h4>Faça login ou crie uma nova conta</h4><br>
  		<button onclick="window.location.href='/accounts/login'" style="margin: 5px;" class="btn btn-success">Login</button>
  		<button onclick="window.location.href='/signup'" style="margin: 5px;" class="btn btn-primary">Cadastre-se</button>
  		</div>
	{% endif %}
	
</div>



{% endblock %}

templates/inpartida.html
{% extends 'base.html' %}

{% block title %}Jogue!{% endblock %}

{% block content %}

    {% if user.is_authenticated %}
        {% for x in object_list %}
            {% if x.allTrue == True %}
                <META http-equiv="refresh" content="0;URL=/game-sucess/">
            {% endif %}

            {% if x.image == 7 %}
                <META http-equiv="refresh" content="0;URL=/game-fail/">
            {% endif %}
        {% endfor %}
        <div style="text-align: center;">
        <h1>Bem vindo a partida</h1><br>
        <button style="float: right; margin-right: 20px;" style="margin: 5px;" onclick="window.location.href='/'"  class="btn btn-success">Home</button>
        <div class="text-relative">
            <h4>A dica é</h4>
            {% for x in images %}
            <p style="text-transform: capitalize">{{x.dica}}</p>
            {% endfor %}
        </div>
        

        {% for x in images %}
        {% if x.image == 1 %}
            <img src="https://uploaddeimagens.com.br/images/001/577/179/full/forca1.png?1535154206" alt="1" width="200" height="200">
        
        {% elif x.image == 2 %}
            <img src="https://uploaddeimagens.com.br/images/001/577/187/full/forca2.png?1535154329" alt="1" width="200" height="200">
        
        {% elif x.image == 3 %}
            <img src="https://uploaddeimagens.com.br/images/001/577/189/full/forca3.png?1535154364" alt="1" width="200" height="200">
        
        {% elif x.image == 4 %}
            <img src="https://uploaddeimagens.com.br/images/001/577/190/full/forca4.png?1535154401" alt="1" width="200" height="200">
        
        {% elif x.image == 5 %}
            <img src="https://uploaddeimagens.com.br/images/001/577/192/full/forca5.png?1535154444" alt="1" width="200" height="200">
        
        {% elif x.image == 6 %}
            <img src="https://uploaddeimagens.com.br/images/001/577/193/full/forca6.png?1535154470" alt="1" width="200" height="200">
        
        {% else %}
            <img src="https://uploaddeimagens.com.br/images/001/577/195/full/forca7.png?1535154500" alt="1" width="200" height="200">
        {% endif %}
        {% endfor %}
        
         <table align="center">
              <tr>

                {% for object in object_list %}
                    {% if object.visible == True %}
                    <th style="font-size: 30px; text-transform: uppercase;">{{object.letra}}</th>
                    {% else %}
                        <th style="font-size: 50px;">-</th>
                    {% endif %}
                {% endfor %}
              </tr>
        </table>

        <form method="POST" class="form-signin">
            {% csrf_token %}
            <button name="Q" value="Q" class="btn btn-secundary" type="submit">Q</button>
            <button name="W" value="W" class="btn btn-secundary" type="submit">W</button>
            <button name="E" value="E" class="btn btn-secundary" type="submit">E</button>
            <button name="R" value="R" class="btn btn-secundary" type="submit">R</button>
            <button name="T" value="T" class="btn btn-secundary" type="submit">T</button>
            <button name="Y" value="Y" class="btn btn-secundary" type="submit">Y</button>
            <button name="U" value="U" class="btn btn-secundary" type="submit">U</button>
            <button name="I" value="I" class="btn btn-secundary" type="submit">I</button>
            <button name="O" value="O" class="btn btn-secundary" type="submit">O</button>
            <button name="P" value="P" class="btn btn-secundary" type="submit">P</button><br>
            <br><button name="A" value="A" class="btn btn-secundary" type="submit">A</button>
            <button name="S" value="S" class="btn btn-secundary" type="submit">S</button>
            <button name="D" value="D" class="btn btn-secundary" type="submit">D</button>
            <button name="F" value="F" class="btn btn-secundary" type="submit">F</button>
            <button name="G" value="G" class="btn btn-secundary" type="submit">G</button>
            <button name="H" value="H" class="btn btn-secundary" type="submit">H</button>
            <button name="J" value="J" class="btn btn-secundary" type="submit">J</button>
            <button name="K" value="K" class="btn btn-secundary" type="submit">K</button>
            <button name="L" value="L" class="btn btn-secundary" type="submit">L</button><br>
            <br><button name="Ç" value="Ç" class="btn btn-secundary" type="submit">Ç</button>
            <button name="Z" value="Z" class="btn btn-secundary" type="submit">Z</button>
            <button name="X" value="X" class="btn btn-secundary" type="submit">X</button>
            <button name="C" value="C" class="btn btn-secundary" type="submit">C</button>
            <button name="V" value="V" class="btn btn-secundary" type="submit">V</button>
            <button name="B" value="B" class="btn btn-secundary" type="submit">B</button>
            <button name="N" value="N" class="btn btn-secundary" type="submit">N</button>
            <button name="M" value="M" class="btn btn-secundary" type="submit">M</button>
        </form>
        </div>

        
        
    {% else %}
        <META http-equiv="refresh" content="0;URL=/"> 
    {% endif %}
{% endblock %}

templates/ranking.html
{% extends 'base.html' %}

{% block title %}Ranking{% endblock %}

{% block content %}

<h1 style="text-align: center;">Só os melhores</h1>
<button onclick="window.location.href='/'" class="btn btn-primary" style="float:right; margin-right: 20px;">Voltar</button>
{% for x in object_list %}
{% for y in x %}
<div class="block-color text-relative" style="text-align: center;">
	<h4 style="text-transform: capitalize">{{y.userName}}</h4>
    <p>Pontos: {{y.Individualpontos}}</p>

  </div>
  
{% endfor %}
{% endfor %}



{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <div class="top-buffer">
    <div class="mx-auto" style="width: 300px;">    
        <form method="POST">
        		{% csrf_token %}
                <div class="col-sm-20 text-center">
                <img class="img-fluid" alt="Responsive image" height="100" width="100" src="https://cdn2.iconfinder.com/data/icons/ourea-icons/256/User_Accounts_256x256-32.png" >

                <input style="margin-top: 10px;"  "type="text" name="username" class="form-control" placeholder="UserName" required id="id_username">
                <p>Não use caracters especiais como: @, #, $</p><br>
                
                <input required type="password" name="password1" class="form-control" placeholder="Senha" id="id_password1"><br>
                <ul style="text-align: left;">
                	<li>Sua senha não pode ser tão parecida com suas outras informações pessoais.</li>
                	<li>Sua senha precisa conter pelo menos 8 caracteres.</li>
                	<li>Sua senha não pode ser uma senha habitualmente utilizada.</li>
                	<li>Sua senha não pode ser inteiramente numérica.</li>
                </ul>
                 

                <input required type="password" name="password2" class="form-control" placeholder="Confirme Senha" id="id_password2"><br>

                <div class="btn-group" role="group" aria-label="Basic example">
                
                <button style="margin: 5px; " type="submit" name="submit" class="btn btn-primary">Cadastrar</button>

                <button onclick="window.location.href='/'" style="margin: 5px;" class="btn btn-secundary">Home</button>

                </div>
                </div>
                <div class="form-group">

        </form>
{% endblock %}

templates/sucess.html
{% extends 'base.html' %}

{% block title %}Game Over{% endblock %}

{% block content %}


    <div id="main" class="block-color" style="text-align: center;">
    {% if user.is_authenticated %}
        <div class="title-h1" ">
        <h1 >Você venceu aeeeee</h1>
        <h3>Ganhou 10 pontos</h3>
        </div>
        <META http-equiv="refresh" content="2;URL=/">
    {% else %}
        <META http-equiv="refresh" content="0;URL=/">
    {% endif %}
    
</div>
{% endblock %}